package main

type BibleBooks struct {
	Data []BibleBook `json:"data"`
}

type BibleBook struct {
	ID           string `json:"id"`
	BibleID      string `json:"bibleId"`
	Abbreviation string `json:"abbreviation"`
	Name         string `json:"name"`
	NameLong     string `json:"nameLong"`
}

var bible_books = BibleBooks{
	Data: []BibleBook{
		{
			ID:           "GEN",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "GEN",
			Name:         "Genesis",
			NameLong:     "Genesis",
		},
		{
			ID:           "EXO",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "EXO",
			Name:         "Exodus",
			NameLong:     "Exodus",
		},
		{
			ID:           "LEV",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "LEV",
			Name:         "Leviticus",
			NameLong:     "Leviticus",
		},
		{
			ID:           "NUM",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "NUM",
			Name:         "Numbers",
			NameLong:     "Numbers",
		},
		{
			ID:           "DEU",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "DEU",
			Name:         "Deuteronomy",
			NameLong:     "Deuteronomy",
		},
		{
			ID:           "JOS",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JOS",
			Name:         "Joshua",
			NameLong:     "Joshua",
		},
		{
			ID:           "JDG",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JDG",
			Name:         "Judges",
			NameLong:     "Judges",
		},
		{
			ID:           "RUT",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "RUT",
			Name:         "Ruth",
			NameLong:     "Ruth",
		},
		{
			ID:           "1SA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1SA",
			Name:         "1 Samuel",
			NameLong:     "1 Samuel",
		},
		{
			ID:           "2SA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2SA",
			Name:         "2 Samuel",
			NameLong:     "2 Samuel",
		},
		{
			ID:           "1KI",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1KI",
			Name:         "1 Kings",
			NameLong:     "1 Kings",
		},
		{
			ID:           "2KI",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2KI",
			Name:         "2 Kings",
			NameLong:     "2 Kings",
		},
		{
			ID:           "1CH",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1CH",
			Name:         "1 Chronicles",
			NameLong:     "1 Chronicles",
		},
		{
			ID:           "2CH",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2CH",
			Name:         "2 Chronicles",
			NameLong:     "2 Chronicles",
		},
		{
			ID:           "EZR",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "EZR",
			Name:         "Ezra",
			NameLong:     "Ezra",
		},
		{
			ID:           "NEH",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "NEH",
			Name:         "Nehemiah",
			NameLong:     "Nehemiah",
		},
		{
			ID:           "TOB",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "TOB",
			Name:         "Tobit",
			NameLong:     "Tobit",
		},
		{
			ID:           "JDT",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JDT",
			Name:         "Judith",
			NameLong:     "Judith",
		},
		{
			ID:           "ESG",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ESG",
			Name:         "Esther",
			NameLong:     "Esther",
		},
		{
			ID:           "1MA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1MA",
			Name:         "1 Maccabees",
			NameLong:     "1 Maccabees",
		},
		{
			ID:           "2MA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2MA",
			Name:         "2 Maccabees",
			NameLong:     "2 Maccabees",
		},
		{
			ID:           "JOB",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JOB",
			Name:         "Job",
			NameLong:     "Job",
		},
		{
			ID:           "PSA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "PSA",
			Name:         "Psalms",
			NameLong:     "Psalms",
		},
		{
			ID:           "PSA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "PSA",
			Name:         "Psalm",
			NameLong:     "Psalm",
		},
		{
			ID:           "PRO",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "PRO",
			Name:         "Proverbs",
			NameLong:     "Proverbs",
		},
		{
			ID:           "ECC",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ECC",
			Name:         "Ecclesiastes",
			NameLong:     "Ecclesiastes",
		},
		{
			ID:           "SNG",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "SNG",
			Name:         "Song of Songs",
			NameLong:     "Song of Songs",
		},
		{
			ID:           "WIS",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "WIS",
			Name:         "Wisdom",
			NameLong:     "Wisdom",
		},
		{
			ID:           "SIR",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "SIR",
			Name:         "Sirach (Ecclesiasticus)",
			NameLong:     "Sirach (Ecclesiasticus)",
		},
		{
			ID:           "ISA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ISA",
			Name:         "Isaiah",
			NameLong:     "Isaiah",
		},
		{
			ID:           "JER",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JER",
			Name:         "Jeremiah",
			NameLong:     "Jeremiah",
		},
		{
			ID:           "LAM",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "LAM",
			Name:         "Lamentations",
			NameLong:     "Lamentations",
		},
		{
			ID:           "BAR",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "BAR",
			Name:         "Baruch",
			NameLong:     "Baruch",
		},
		{
			ID:           "EZK",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "EZK",
			Name:         "Ezekiel",
			NameLong:     "Ezekiel",
		},
		{
			ID:           "DAG",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "DAG",
			Name:         "Daniel",
			NameLong:     "Daniel",
		},
		{
			ID:           "HOS",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "HOS",
			Name:         "Hosea",
			NameLong:     "Hosea",
		},
		{
			ID:           "JOL",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JOL",
			Name:         "Joel",
			NameLong:     "Joel",
		},
		{
			ID:           "AMO",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "AMO",
			Name:         "Amos",
			NameLong:     "Amos",
		},
		{
			ID:           "OBA",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "OBA",
			Name:         "Obadiah",
			NameLong:     "Obadiah",
		},
		{
			ID:           "JON",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JON",
			Name:         "Jonah",
			NameLong:     "Jonah",
		},
		{
			ID:           "MIC",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "MIC",
			Name:         "Micah",
			NameLong:     "Micah",
		},
		{
			ID:           "NAM",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "NAM",
			Name:         "Nahum",
			NameLong:     "Nahum",
		},
		{
			ID:           "HAB",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "HAB",
			Name:         "Habakkuk",
			NameLong:     "Habakkuk",
		},
		{
			ID:           "ZEP",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ZEP",
			Name:         "Zephaniah",
			NameLong:     "Zephaniah",
		},
		{
			ID:           "HAG",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "HAG",
			Name:         "Haggai",
			NameLong:     "Haggai",
		},
		{
			ID:           "ZEC",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ZEC",
			Name:         "Zechariah",
			NameLong:     "Zechariah",
		},
		{
			ID:           "MAL",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "MAL",
			Name:         "Malachi",
			NameLong:     "Malachi",
		},
		{
			ID:           "MAT",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "MAT",
			Name:         "Matthew",
			NameLong:     "Matthew",
		},
		{
			ID:           "MRK",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "MRK",
			Name:         "Mark",
			NameLong:     "Mark",
		},
		{
			ID:           "LUK",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "LUK",
			Name:         "Luke",
			NameLong:     "Luke",
		},
		{
			ID:           "JHN",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JHN",
			Name:         "John",
			NameLong:     "John",
		},
		{
			ID:           "ACT",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ACT",
			Name:         "Acts of the Apostles",
			NameLong:     "Acts of the Apostles",
		},
		{
			ID:           "ACT",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ACT",
			Name:         "Acts",
			NameLong:     "Acts of the Apostles",
		},
		{
			ID:           "ROM",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "ROM",
			Name:         "Romans",
			NameLong:     "Romans",
		},
		{
			ID:           "1CO",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1CO",
			Name:         "1 Corinthians",
			NameLong:     "1 Corinthians",
		},
		{
			ID:           "2CO",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2CO",
			Name:         "2 Corinthians",
			NameLong:     "2 Corinthians",
		},
		{
			ID:           "GAL",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "GAL",
			Name:         "Galatians",
			NameLong:     "Galatians",
		},
		{
			ID:           "EPH",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "EPH",
			Name:         "Ephesians",
			NameLong:     "Ephesians",
		},
		{
			ID:           "PHP",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "PHP",
			Name:         "Philippians",
			NameLong:     "Philippians",
		},
		{
			ID:           "COL",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "COL",
			Name:         "Colossians",
			NameLong:     "Colossians",
		},
		{
			ID:           "1TH",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1TH",
			Name:         "1 Thessalonians",
			NameLong:     "1 Thessalonians",
		},
		{
			ID:           "2TH",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2TH",
			Name:         "2 Thessalonians",
			NameLong:     "2 Thessalonians",
		},
		{
			ID:           "1TI",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1TI",
			Name:         "1 Timothy",
			NameLong:     "1 Timothy",
		},
		{
			ID:           "2TI",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2TI",
			Name:         "2 Timothy",
			NameLong:     "2 Timothy",
		},
		{
			ID:           "TIT",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "TIT",
			Name:         "Titus",
			NameLong:     "Titus",
		},
		{
			ID:           "PHM",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "PHM",
			Name:         "Philemon",
			NameLong:     "Philemon",
		},
		{
			ID:           "HEB",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "HEB",
			Name:         "Hebrews",
			NameLong:     "Hebrews",
		},
		{
			ID:           "JAS",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JAS",
			Name:         "James",
			NameLong:     "James",
		},
		{
			ID:           "1PE",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1PE",
			Name:         "1 Peter",
			NameLong:     "1 Peter",
		},
		{
			ID:           "2PE",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2PE",
			Name:         "2 Peter",
			NameLong:     "2 Peter",
		},
		{
			ID:           "1JN",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "1JN",
			Name:         "1 John",
			NameLong:     "1 John",
		},
		{
			ID:           "2JN",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "2JN",
			Name:         "2 John",
			NameLong:     "2 John",
		},
		{
			ID:           "3JN",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "3JN",
			Name:         "3 John",
			NameLong:     "3 John",
		},
		{
			ID:           "JUD",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "JUD",
			Name:         "Jude",
			NameLong:     "Jude",
		},
		{
			ID:           "REV",
			BibleID:      "b907c8622b59a1f7-01",
			Abbreviation: "REV",
			Name:         "Revelation",
			NameLong:     "Revelation",
		},
	},
}
