version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      - PORT=${PORT}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - OLLAMA_URL=http://host.docker.internal:11434
      - TZ=Asia/Manila
      - API_TOKEN=${API_TOKEN}
      - BIBLE_ID=${BIBLE_ID}


